services:
  loymax_rag_app:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./vector_db:/app/vector_db
    env_file:
      - configs/.env
    restart: unless-stopped
