preprocessing:
  quality_check: true          # Проверка структуры и пустых текстов перед обработкой
  lowercase: true              # Приведение текста к нижнему регистру
  clean_text:                  # Шаги очистки текста
    clear_html: true
    clear_broken_bits: true
    clear_invisible_spaces: true
    clear_tabs_and_line_breaks: true
    clear_multiple_spaces: true
  check_empty_doc: true        # Исключать документы с пустым текстом
  remove_duplicates:
    by_id: true                # Удаление дублей по uid
    by_hash: true              # Удаление дублей по хешу текста
  filter_by_length:
    working: true              # Фильтровать короткие тексты
    min_length: 20             # Минимальная длина текста (символов)

embedder:
  model_name: "ai-forever/sbert_large_mt_nlu_ru"  # Модель SentenceTransformer

answer_generator:
  llm_model_name: "gpt-4o"     # LLM-модель для генерации ответов
  prompt: |                    # Инструкция для модели (ответ строго по контексту)
    Ответь на вопрос, используя только приведённый ниже контекст.
    Не используй внешние знания или догадки.
    Если в контексте нет данных для ответа на вопрос, скажи: 
    "В предоставленном контексте нет информации для ответа на этот вопрос".
  top_k: 5                     # Кол-во релевантных фрагментов из базы

api_model_names:
  openai_models:
    - gpt-4o
    - gpt-4.1
    - gpt-3.5-turbo

  anthropic_models:
    - claude-opus-4-20250514
    - claude-sonnet-4-20250514
    - claude-3-7-sonnet-20250219
    - claude-3-5-haiku-20241022
    - claude-3-5-sonnet-20241022-v2

  google_models:
    - gemini-1.5-pro
    - gemini-2.5-pro
