preprocessing:
  quality_check: true
  lowercase: true
  clean_text:
    clear_html: true
    clear_broken_bits: true
    clear_invisible_spaces: true
    clear_tabs_and_line_breaks: true
    clear_multiple_spaces: true
  check_empty_doc: true
  remove_duplicates:
    by_id: true
    by_hash: true
  filter_by_length:
    working: true
    min_length: 20

embedder:
  model_name: "ai-forever/sbert_large_mt_nlu_ru"

answer_generator:
  llm_model_name: "gpt-4o"
  prompt: "Дай максимально развернутый и полезный ответ, основываясь только на приведённом контексте. Если в контексте нет информации, отвечающей на вопрос, то скажи, что ты не знаешь как ответить на данный вопрос."
  top_k: 5

api_model_names:
  openai_models:
    - gpt-4o
    - gpt-4.1
    - gpt-3.5-turbo

  anthropic_models:
    - claude-opus-4-20250514
    - claude-sonnet-4-20250514
    - claude-3-7-sonnet-20250219
    - claude-3-5-haiku-20241022
    - claude-3-5-sonnet-20241022-v2

  google_models:
    - gemini-1.5-pro
    - gemini-2.5-pro
